# Generated by Django 5.1 on 2024-08-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RomanDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(default='Apicius', max_length=100)),
                ('ingredients', models.TextField()),
                ('preparation', models.TextField()),
                ('historical_context', models.TextField(blank=True, null=True)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
