# Generated by Django 5.1 on 2024-08-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_romandish_delete_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='romandish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images/'),
        ),
        migrations.AddField(
            model_name='romandish',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
